name: C++
on:
  push:
    branches: ["main", "drecom/develop"]
  pull_request:
    branches: ["main", "drecom/develop"]
jobs:
  windows-latest:
    runs-on: 'windows-latest'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Get GoogleTest
      run: git submodule update --init
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2      
    - name: Build
      run: |
        mkdir CPP/build
        cd CPP/build
        cmake .. -DCLIPPER2_TESTS=ON -DCLIPPER2_UTILS:BOOL=ON -DCLIPPER2_EXAMPLES:BOOL=ON
        cmake --build . --config RelWithDebInfo --parallel
    - name: Run tests
      run: |
        cd CPP/build
        ctest . -C RelWithDebInfo --output-on-failure
  ubuntu-latest-clang-default:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Get GoogleTest
      run: git submodule update --init
    - name: Build
      run: |
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        mkdir CPP/build
        cd CPP/build
        cmake .. -DCLIPPER2_TESTS=ON
        make
    - name: Run tests
      run: |
        cd CPP/build
        env CTEST_OUTPUT_ON_FAILURE=1 make test
  macos-latest:
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Get GoogleTest
      run: git submodule update --init
    - name: Build
      run: |
        mkdir CPP/build
        cd CPP/build
        cmake .. -DCLIPPER2_TESTS=ON
        make
    - name: Run tests
      run: |
        cd CPP/build
        env CTEST_OUTPUT_ON_FAILURE=1 make test
